# fly.toml file generated for web-reducer-client on 2022-06-07T18:43:30-05:00

app = "web-reducer-client"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[statics]]
  guest_path = "/usr/src/app/public"
  url_prefix = "/"

[env]
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/heartbeat"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = true
    [services.http_checks.headers]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
