version: "3"
services:
  db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  secrets_db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=hook_secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./secrets-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
  code_runner:
    build: ./runner
    environment:
      PORT: 3002
    ports:
      - 3002:3002
  secrets:
    build: ./secrets
    ports:
      - 3003:3003
    environment:
      DATABASE_URL: postgres://postgres:postgres@secrets_db:5432/hook_secrets
      PORT: 3003
      ENCRYPTION_SECRET: foobarbaz
    depends_on:
      - secrets_db
