version: "3"
services:
  db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  authn:
    image: keratin/authn-server:1.13.0
    ports:
      - "8765:3003"
    command: >
      /bin/sh -c "
        sleep 6;
        ./authn migrate;
        ./authn server;
      "
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hook
      - REDIS_URL=redis://redis:6379/1
      - AUTHN_URL=http://authn:3003
      - APP_DOMAINS=localhost
      - SECRET_KEY_BASE=foobarq
      - HTTP_AUTH_PASSWORD=admin
      - HTTP_AUTH_USERNAME=admin
      - GITHUB_OAUTH_CREDENTIALS=Iv1.9d7918856dacd8a3:57132675057c026b3896c53ab380f0d341647406
    depends_on:
      - redis
      - db

  code_runner:
    build: ./runner
    ports:
      - 3002:3002

  timescale_db:
    volumes:
      - ./timescale-data:/var/lib/postgresql/data
    image: timescaledev/timescaledb-ha:pg12-latest
    ports:
      - 2345:5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  promscale:
    image: timescale/promscale:0.7
    ports:
      - 9201:9201/tcp
      - 9202:9202
    # restart: on-failure
    depends_on:
      - timescale_db
    restart: on-failure
    command:
      ["-enable-feature=tracing", "-otlp-grpc-server-listen-address=:9202"]
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@timescale_db:5432/postgres?sslmode=allow

  otel_collecter:
    platform: linux/x86_64
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 55678-55679:55678-55679
      - 4317:4317
      - 4318:4318
      - 8888:8888
      - 9411:9411
    volumes:
      - ./otel-config.yaml:/otel-local-config.yaml
    command: ["--config=/otel-local-config.yaml"]
