version: "3"
services:
  db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  secrets_db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=hook_secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./secrets-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
  code_runner:
    build: ./runner
    ports:
      - 3002:3002
