version: "3"
# This volume is used as communication mechanism between
# the migrator and the test runner
volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=1000"
services:
  db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  secrets_db:
    image: supabase/postgres:13.3.0
    shm_size: 2g
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=hook_secrets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./secrets-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
  code_runner:
    build: ../runner
    environment:
      PORT: 3002
    ports:
      - 3002:3002
  web:
    build: ../client
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
      REDIS_URL: redis://redis:6379/0
      PORT: 3000
      BACKEND_URL: http://server:3001
      JWT_SECRET: asdf
      COOKIE_SECRET: asdf
  secrets:
    build: ../secrets
    ports:
      - 3003:3003
    environment:
      DATABASE_URL: postgres://postgres:postgres@secrets_db:5432/hook_secrets
      PORT: 3003
      ENCRYPTION_SECRET: foobarbaz
    depends_on:
      - secrets_db
  migrator:
    build: ./migrator
    volumes:
      - shared-tmpfs:/tmp/shared
      - ../server/migrations:/usr/src/app/migrations
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/hook
      MIGRATOR_NAME: server
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
    restart: on-failure
  secrets_migrator:
    build: ./migrator
    volumes:
      - shared-tmpfs:/tmp/shared
      - ../secrets/migrations:/usr/src/app/migrations
    environment:
      DATABASE_URL: postgres://postgres:postgres@secrets_db:5432/hook_secrets
      MIGRATOR_NAME: secrets
      DATABASE_HOST: secrets_db
      DATABASE_PORT: 5432
    depends_on:
      - secrets_db
    restart: on-failure
  server:
    build: ../server
    ports:
      - 3001:3001
      - 9464:9464
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/hook
      REDIS_URL: redis://redis:6379/0
      ROARR_LOG: "false"
      PORT: 3001
      RUNNER_URL: http://code_runner:3002
      JWT_SECRET: asdf
      SECRET_ACCESS_KEY_KEY: aaaa
      SECRETS_URL: http://secrets:3003
    depends_on:
      - secrets
      - redis
      - migrator
  http_tests:
    build: ./http-tests
    volumes:
      - shared-tmpfs:/tmp/shared
    environment:
      SERVER_URL: http://server:3001
      WEB_URL: http://web:3000
      JWT_SECRET: asdf
      COOKIE_SECRET: asdf
      DATABASE_URL: postgres://postgres:postgres@db:5432/hook
      SECRETS_DATABASE_URL: postgres://postgres:postgres@secrets_db:5432/hook_secrets
      JEST_ARGS: ${JEST_ARGS}
      RUNNER_URL: http://code_runner:3002
      SECRETS_URL: http://secrets:3003
    # https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1
    depends_on:
      - server
      - secrets_db
      - secrets
      - db
      - migrator
      - code_runner
