# fly.toml file generated for web-reducer-runner on 2022-06-07T16:25:38-05:00

app = "web-reducer-runner"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true
