# fly.toml file generated for web-reducer-secrets on 2022-06-07T18:23:57-05:00

app = "web-reducer-secrets"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "yarn migrate up"